
# Physique et Chimie
questionJaune = [["Quel est le domaine visible de la lumière ?", "A : [400:800] m", "B : [400,800] nm", "C : [400,800] μm", "B"],
                 ["Quelle est la formule brut de l'acide sulfurique ?", "A : HNO3", "B : H2CO3", "C : H2SO4", "C" ],
                 ["Quelle est la loi de Beer-Lambert ?", "A : A = ε x l x C", "B : σ = k x C", "C : σ = λ x C", "A"],
                 ["Quelle est la vitesse de la lumière ?", "A : 3 000 000 cm/s ","B : 3 000 000 m/s" , "C =  300 000 km/s", "C",],
                 ["Quelle est la seconde loi de Newton ?", "A : F= m*a", "B : F= m*g", " C : F= m/a", "A"],
                 ["A quelle famille appartient les elements chimique de la deuxième colonne du tableau périodique des éléments ?","A : Halogènes", "B : Alcalino-terreux", "C : Gaz nobles", "B"],
                 ["Quelle est la température d'ébullition de l'eau ?", "A : 100 °C", "B : 95 °C", "C : 130 °C", "A"],
                 ["Qu'est ce qu'une espèce amphotère ?", "A : une espèce qui peut être acide \n et basique","B : une espèce qui est uniquement \n acide","C : une espèce qui est uniquement \n basique", "A"],
                 ["Quelle est la formule du pH ?", "A : pH= [H3O+]*log(10)", "B : pH= -log[H3O+]", "C : pH= -log[HO-]", "B"],
                 ["Quel philosophe a participé au progrés de la chimie ?", "A : Descartes", "B : Archimède", "C : Machiavel", "A"],
                 ["Un acide peut...?", "A : libérer un proton H+", "B : capter un proton H+", "C : faire backgroundre un os", "A"],
                 ["Les réactifs titrés et titrants sont introduits dans des proportions stoechiométrique", "A : au milieu", "B : à l'équivalence", "C : à l'équilibre", "B"],
                 ["Que signifie CAN ?", "Convertisseur Antologique Numérisé", "B : Convertisseur Arithmétique Numérique", "C : Convertisseur Analogique Numérique", "C"],
                 ["un octet...", "A : code 256 valeurs", "B : 8 valeurs", "C : 64 valeurs", "A"],
                 ["quel est l'unité SI de base du Joule (J)", "A : kg.m2.s−2", "B : B : kg.m.s-2", "C : kg.m2.s-1", "A"],
                 ["Quelle est la formule de l'acide chlorydrique", "A : Cl", "B : ACl", "C : HCl", "C"],
                 ["Quelle(s) précaution(s) prendre; à part la blouse; \n pour manipuler  un produit corrosif ?", "A : une hotte", "B : gants et lunettes", "C : un chiffon", "B"],
                 ["Lors d'un dosage par étalonnage, il faut d'abord...?", "A : faire le blanc", "B : calculer l'absorbance de la solution", "C : rajouter de l'eau distillée", "A"],
                 ["Un faisceau laser est une onde ...?", "A : polychromatique", "B : monochromatique", "C : chromatique", "B"],
                 ["Le son est plus rapide dans ?", "A : l'air", "B : l'eau", "C : la matiére", "B"],
                 ["Un son est perçu plus aigu lorsque l'on...?", "A : s'approche de l'émetteur", "B : s'éloigne de l'émetteur", "C : augmente le volume", "A"]]

# Philosophie et Français
questionBleue = [["Quel philosophe est pessimiste ?", "A : Schopenhauer", "B : Rousseau", "C : Eisenhower","A"],
                 ["Qui est l'auteur des ''Pensées'' ?", "A : Pascal", "B : Aristote", "C : Hegel", "A"],
                 ["Qu'est-ce que l'aliénation ?", "A : être déposséder de soi", "B : accoucher de ses pensées", "C : agir avec contrainte", "A"],
                 ["Qu'est-ce que la maïeutique ?", "A : une technique", "B : un art", "C : une mosaïque", "B"],
                 ["comment appelle-t-on un vers à 12 syllabes ?", "A : Alexandrin", "B : Octosyllabe", "C : Décasyllabe", "A"],
                 ["quelle figure de style associe directement \n un comparé à un comparant ?", "A : Comparaison", "B : Antithèse", "C : Métaphore", "C"],
                 ["Parmi ces auteurs lequel est un philosophe du contract ?","A : Pascal","B : Hobbes","C : Spinoza","B"],
                 ["Quel auteur dit <L'obéissance à la loi qu'on s'est \n prescrite est liberté> ?","A : Rousseau","B : Lévi-Strauss","C : Clastres ","A"],
                 ["Comment se nome la figure de style qui designe \n l'amplification d'un mot ?","A : l'éxagération","B : L'hyperbole","C : La disproportion","B"],
                 ["qu'est ce qui est inscrit sur le temple de Delphe ?", "A : Connait toi toi-même", "B : Aide ton prochain", "C : Sois humble", "A"],
                 ["Qu'est ce qui s'oppose au droit positif ?", "A : le droit négatif", "B : le droit naturel", "C : le droit humain", "B"],
                 ["Compléter : << L'Homme est un roseau...", "A : perdant", "B : faible", "C : pensant", "C"],
                 ["A quoi s'oppose la justice commutative ?", "A : la justice additive", "B : la jusice distributive", "C : la justice humaine", "B"],
                 ["Selon Kant le bonheur est...", "A : de la raison pure", "B : de l'imagination", "C : un désir", "B"],
                 ["Qui est le philosophe des petites perçeptions ?", "A : Kant", "B : Rousseau", "C : Leibniz", "C"],
                 ["Autrui est le médiateur indispensable...", "A : entre Moi et Moi-même", "B : Moi et ça", "C : Moi et surmoi", "A"],
                 ["Quelles sont les trois instances psychiques selon Freud", "A : Moi, surmoi et ça", "B : ich, Überich et falsch", "C : Moi, autrui et ça", "A"],
                 ["L'expérience de la honte est évoqué par...", "A : Freud", "B : René Girard", "C : Sartre", "C"],
                 ["A quoi correspond le dualisme Cartésien ?", "A : Corp et Esprit", "B : Bien et Mal", "C : Le doute et la Raison", "A"],
                 ["Quel philosophe pense pense qu'à l'état de nature \n l'Homme est un loup pour l'Homme ?", "A : Rousseau", "B : Hobbes", "C : Spinoza", "B"],
                 ["Quel philosophe définit l'Homme comme un \n animal politique ?", "A : Aristote", "B : Hobbes", "C : Rousseau", "A"],
                 ["Dans << Le Prince >>, Machiavel \n présente une philosophie...", "A : immorale", "B : intolérante", "C : amorale", "C"],
                 ["Pour Spinoza << La fin de l'Etat \n est donc en réalité...>>", "A : La domination", "B : Le pouvoir", "C : La liberté", "C"],
                 ["Qu'est ce que l'anarchie ?", "A : Le Chaos social", "B : Le refus de l'autorité politique", "C : le communisme", "B"],
                 ["Selon Weber l'Etat detient le monopole...", "A : De violence physique", "B : De la violence morale", "C : De la violence gratuite", "A"],
                 ["Selon Freud les rêves sont...", "A : Refoulés", "B : La voie royale pour l'inconscient", "C : Une illusion de l'inconscient", "B"],
                 ["Qui dit je est un autre ?", "A : Rimbaud", "B : Nietzsche", "C : Sartre", "A"],
                 ["Selon Kant, quand un artist commence son travail ...","A : il doit demander conseil","B : il ne peut pas avoir ue immage présice du résultat","C : il a besoin d'un modèle précis","B"],
                 ["Selon Kant le génie est ","A : universel","B : subjectif","C : individuel","B"],
                 ["Pendant des siècles, l'art avait la même définition que","A : métier","B ; technique","C : travail","B"],
                 ["Complétez la phrase de Klee \n << L'art ne produit pas le visible mais...","A : montre le réel","B : dévoile le monde","C : rend visible","C"]]

# Anime et manga
questionNoire = [["Quand dragon ball est-il sorti ?", "A : 1985", "B : 1992", "C : 1984", "C"],
                 ["Quelle est le mot préféré de Nero Claudius dans Fate/Extra ?", "A : Yay", "B : Umu", "C : dattebayo", "B"],
                 ["Qui est l'auteur de One Piece ?", "A : Hiro Mashima", "B : Eiichiro Oda", "C : Masashi Kishimoto", "B"],
                 ["quel mot en japonais est utilisé pour appeler son aîné ?", "A : sensei", "B : kōhai", "C : senpai", "C"],
                 ["lequel de ces plats n'appartient pas au Japon ?", "A : Gyoza", "B : sushi", "C : Mapo Tofu", "C"],
                 ["Que signifie SAO ?", "A : Sword Art Online", "B : Swim Art Office", "C : Swear As Origine", "A"],
                 ["Combien de classe de servant existe dans Fate Stay Night ?", "A : 8", "B : 7", "C : 9", "B"],
                 ["comment s'appelle le 1er bateau des chapeaux de pailles ?", "A : Vogue Merri", "B : Vogue Mery", "C : Vogue Merry", "C"],
                 ["Opening 1 de sword Art Online", "A : Catch The Moment de LiSA", "B : Crossing Field de LiSA", "C : Rising Hope de LiSA", "B"],
                 ["Opening 1 de sword Art Online II", "A : Ignite de Eir Aoi", "INNOCENCE de Eir Aoi", "C : KASUMI de Eir Aoi", "A"],
                 ["Combien d'opening possède Naruto Shippuden ?", "A : 20 openings", "B : 18 openings", "C : 25 openings", "A"],
                 ["En combien d'épisode c'est terminé Naruto Shippuden ?", "A : 600 épisodes", "800 épisodes", "C : 500 épisodes", "C"],
                 ["Lequel de ces animes n'est pas un anime de sport ?", "A : Kuroko no Basket", "Shokugeki no Soma", "C : Haikyuu", "B"],
                 ["Quel anime sort une phrase philosophique à chaque épisode ?", "A : Classroom crisis", "B : Classroom of the Elite", "C : Assassination Classroom", "B"],
                 ["Comment appelle-t-on les sabres des Shinigami dans Bleach ?", "A : Zanpakutō", "B : Nihontō", "C : Shinokyōfu", "A"],
                 ["Fairy Tail est un manga où...","A : des personnes cherchent le One Piece", "B : des personnes veulent manger le plus", "C : des personnes utilisent de la magie", "C"],
                 ["quelle est le nom de Sanji dans One piece ?", "A : Vinsmoke", "B : Vimsnoke", "C : Vinmoke", "A"],
                 ["Opening 2 de Fate Stay Night UBW", "A : Last Stardust de Aimer", "B : Ninelie de Aimer", "C : Brave Shine de Aimer", "C"],
                 ["Comment s'appelle la 1ère supertechnique de Axel Blaze \n dans Inazuma eleven ?", "A : Tempête de feu", "B : Tornade de feu", "C : tourbillon de feu", "B"],
                 ["Comment s'appelle la 1ère supertechnique de Mark Evans \n dans Inazuma eleven ?", "A : Main Celeste", "B : Main Magique", "C : Main de l'infinie", "A"],
                 ["Chopper de One piece est...", "A : Un Cerf", "B : Un Faon", "C : Un Renne", "C"],
                 ["Shokugeki no soma est un manga sur...", "A : sur la cuisine", "B : sur la boxe", "C : sur la natation", "A"],
                 ["Free est un anime sur...", "A : les prix d'Intermarché", "B : sur la gratuité des produits", "C : sur la natation", "C"],
                 ["Death note est un manga parlant...", "A : d'un stylo pouvant tué des gens", "B : d'un cahier de la mort", "C : d'un papier pouvant tout couper", "B"],
                 ["Inazuma eleven est un anime sur...", "A : le basketball", "B : le surf", "C : le football", "C"],
                 ["eyeshield 21 ets un manga sur...", "A : la musique", "B : le football américain", "C : la course", "B"],
                 ["Hunter x Hunter a subi une remasterisation, \n mais en quelle année ?", "A : 2007", "B : 2011", "C : 2014", "B"],
                 ["Beaucoup de manga se passe dans lieu précis, lequel ?", "A : un monde fantastique", "B : un manoir", "C : un lycée", "C"],
                 ["De quel jeu vidéo s'est inspiré Hiro Mashima pour son \n manga Fairy Tail?", "A : Monster Hunter", "B : Dragon quest", "C : Final Fantasy", "B"],
                 ["Quel est le genre de manga qui se passe dans la vie de \n tous les jours?", "A : slice of life", "B : school life", "C : shonen", "A"],
                 ["Boruto est ...", "A : une suite logique à Naruto", "B : un spin-off", "C : un nolife", "B"]]

# Histoire et Géograhie
questionOrange = [["Quand a été proclamé la République populaire de Chine ?", "A : 1946", "B : 1899", "C : 1949", "C"],
                  ["Quel est le nom du mouvement des Juifs voulant rejoindre \n leur terre d'origine ?", "A : Sionisme", "B : Siaunisme", "C : Retour aux originisme", "A"],
                  ["En quelle année Yuri Gagarine est-il allé dans l'espace ?", "A : 1957", "B : 1963", "C : 1961", "C"],
                  ["Qui est l'auteur de ''La France de Vichy'' ?", "A : Robert Paxton", "B : Eric Zemmour", "C : Alain Resnais", "A"],
                  ["Quelle organisation détient les 2/3 du commerce mondiale ?", "A : la Triade", "B : les FTN", "C : Donald Trump", "A"],
                  ["Qu'est-ce que l'Oural ?", "A : une montagne", "B : une faille", "C : une chaîne de montagnes", "C"],
                  ["Qu'est-ce qu'une ville de plus de 10 millions d'habitants ?", "A : mégalopole", "B : métropole", "C: mégapole","C"],
                  ["Que veut dire EVP ? ", "A : Enfants Vietnamien par Pays","B : Etat Vraiment Puissant","C : Equivalant Vingt Pieds","C"],
                  ["Quesqu'un pays enclavé ?","A : un pays sans ressources","B : un pays sans acces à la mer ?","C : un pays sans acces aérien","B"],
                  ["Qui manifestait lors de Mai 68 ?", "A : les cadres", "B : les ouvriers", "C : les ouvriers et les étudiants", "C"],
                  ["Qu'est-ce que les Trente Glorieuses ?", "A trente années de paix", "B : trente années de dictature", "C : trente années de construction \n démocratique", "A"],
                  ["En quelle année l'URSS a-t-elle disparu ?","A: 1990","B : 1991","C : 1992","B"],
                  ["Quand est mort Charles De Gaulle","A : Novembre 1970","B : Août 1971",'C : Décembre 1972',"A"],
                  ["En quelle année est mort Jean Moulin ?","A : 1942","B : 1940","C : 1943","C"],
                  ["Quesqu'une ONG ?","A : Organisation Né au Gabon","B : Organisation Non Gouvernemental","C : Oscar de Nouvelle Guinée"],
                  ["En quelle année eu lieu le procès de Adolf Eichmann ?","A : 1965","B : 1964","C : 1961","C"],
                  ["A l'issu de quelle conférence fut créée l'ONU ?","A : conférence de Yalta","B : conférence de Bretton Woods","C : conférence de San Francisco","C"],
                  ["En quelle année fut créée la CIA ? ","A : 1946","B : 1947","C : 1949","B"],
                  ["Qui était Robert Paxton ?","A : un historien","B : un ministre","C : un président","A"],
                  ["En quelle année fut lancé le Tiers-Monde ?","A : en 1950","B : en 1955","C : en 1952","C"],
                  ["En quelle année fut proclamé l'indépendance de l'Inde ?","A : en 1945"," B : en 1939","C : en 1947","C"],
                  ["Le 'Grand Bond en avant' est une politique \n économique Chinoise lancé en ..","A : 1958","B : 1956","C : 1955","A"],
                  ["Lequel de ces pays ne possède pas un morceau \n de Sahara dans son territoire ?","A : Le Sudan","B : Le Mali","C : le Nigeria","C"],
                  ["Dans quel pays les Etats-Unis interviennent-ils en 2001 ?","A : en Afghanistan","B : en Iran","C : en Irak","A"],
                  ["Qui accède au pouvoir en Irak à partir de 1979 \n et y établit une dictature ?","A : Saddam Hussein","B : Yasser Arafat","C : Moubarak","A"],
                  ["A quels mouvements nationalistes arabes \n l'URSS accorde-t-elle son soutien ?","A : au Likoud israélien","B : à Nasser en Egypte","C : au parti Baas en Syrie","B"],
                  ["Quel pays indépendant est envahi par la Chine \n communiste de Mao et en quelle année?","A : le Tibet en 1950","B : le Cambodge en 1969","C : la Corée en 1953","A"]]

# Mathématiques
questionRouge = [["quel est la limite de 2 + 1/x en +l'infini ?", "A : +l'infini", "B : 0", "C : 2", "C"],
                 ["Comment appele-t-on l'ensemble de tous \n les résultats d'une aléatoire ?","A : Univers", "B : Galaxie", "C : Livre", "A"],
                 ["Quel est le contraire d'une dérivé ?", "A : une vitesse", "B : une primitive", "C : une accélération", "B"],
                 ["La courbe de la fonction ln(x) admet une asymptote \n verticale, mais de quelle équation ?", "A : x = 1", "B : x = 0", "C : x = log(10)", "B"],
                 ["Que vaut e^ln(37) ?","A : ln(37)","B : e^37","C : 37","C"],
                 ["Que vaut (0,9)^n lorsque n tend vers +l'infini?","A : +l'infini",'B : 0',"C : 0,9","B"],
                 ["que vaut e^x avec x = o", "A : 1", "B : 2,7", "C : 0", "A"],
                 ["Une loi exponentielle est ...?", "A : sans mémoire", "B : la réciproque de loi logarithme", "C : toujours négative", "A"],
                 ["Quelle courbe représente une loi normale?", "A : courbe d'Epérion", "B : courbe de cloche", "C : courbe de Gauss", "C"],
                 ["Comment note-on la partie réelle d'un nombre imaginaire z ?", "A : Re(z)", "B : a", "C : Im(z)","A"],
                 ["Avec quel triangle peut-on calculer un coefficient binomial ?", "A : le triangle des Bermudes", "B : le triangle rectangle", "C : le triangle de Pascal","C"],
                 ["Le théorème de bijection monotone est aussi appelé ?", "A : TVI", "B : TNI", "C : TGV", "A"],
                 ["Qu'est-ce que la  représentation paramétrique d'une droite ?", "A : une équation", "B : un système", "C : un produit scalaire", "B"],
                 ["Le nombre exponentiel e vaut...", "A : 2,17", "B : 3,14", "C : 0", "A"],
                 ["Quel est la derivé de 1/u ","A : -u'/u^2","B : -u/u^2","C : -u'/u","A"],
                 ["Quel est la dérivé de u * v","A : u'v'+uv","B : u'v+u'v","C : u'v+uv'","C"],
                 ["Quel est la dérivé de √u","A : u'/(2*u)","B : u'/(2√u)","C : u/(2√u)","B"],
                 ["Quel est la dérivé de U^n","A : n*u'*(u^n-1)","B : n*u*(u^n-1)","C : n*u'*(u^n)"],
                 ["Pour la fonction exponentielle e^-x est équivalant à","A : e^x","B : e^x/x","C : 1/e^x","C"],
                 ["Pour la fonction exponentielle e^(x+y) est équivalant à","A : e^y/e^x","B : e^x/e^y","C : e^x * e^y","C"],
                 ["La fonction exponentielle est toujours","inférieur à O","constante","supérieur à 0","C"],
                 ["Quel est la dérivé de e^u","A : u*e^u","B : u'*e^u'","C : u'*e^u","C"],
                 ["ln(a/b) est équivalant à","A : ln(a)/ln(b)","B : ln(a)+ln(b)","C : ln(a) - ln(b)","C"]]

# SVT et Anglais
questionVerte = [["When J.F.Kennedy die ?", "A : 22 nov 1963", "B : 15 march 1960", "C : 20 nov 1962", "A"],
                 ["What's the french for beaming ?", "A : souriant", "B : radieux", "C : explosif", "B"],
                 ["what does LMAO mean ?", "A : laughing my ass off", "B : lol my ass on", "C : like my ass octopus", "A"],
                 ["Où naissent les lymphocytes?", "A : Moelle épinière", "B : Thymes", "C : Moelle osseuse", "C"],
                 ["Quel concept explique les différences d'altitudes \n entre croûte continentale et océanique?", "A : Isomérie", "B : Isostasie", "C : Isothérmie", "B"],
                 ["Comment appele-t-on la coopération entre animaux \n et plantes au cours du temps ?", "A : Collaboration", "B : Symbiose", "C : Coévolution", "C"],
                 ["Quel est le nom de la phase de réplication des \n cellules reproductrices ?", "A : Mitose", "B : Méiose", "C : Miose", "B"],
                 ["Quelles cellules sont responsables de la \n réaction inflammatoire","A : les lymphocytes","B : les phagocytes","C : les cellules sentinelles","C"],
                 ["Que sont les anticorps ?","A : des protéines","B : des molécules","C : des cellules","A"],
                 ["que signifie LTc ?", "A : Lymphocyte T cytoplasmique", "Lymphocyte T cytoxique", "C : Lymphocyte T cytotoxique", "C"],
                 ["L'andésite est une roche...?", "A : magmatique", "B : plutonique", "C : ophiolitique", "A"],
                 ["L'Homme a un génome trés proche d'un primate, mais lequel?","A : l'Ourang Outan", "B : le chimpanzé", "C : le bonobo","B"]]

# Culture Générale
questionViolette = [["Capitale de la Mongolie ?", "A : Calcutta", "B : Oulang-Bator", "C : Achgabat", "B"],
                    ["Capitale du Cambodge ?", "A : Phnom penh", "B : Battambang", "C : Kratie", "A"],
                    ["Comment s'appelle le tableau regroupant tous les atomes", "A : tableau de signe", "B : tableau de Mendeleïev", "C : tableau de Einstein","B"],
                    ["Qui est la mère du Prince Albert II de Monaco?", "A : Ingrid Donatello", "B : Grace Kelly", "C : Emmanuelle de Monaco", "B"],
                    ["Quelle est la troisième couleur du drapeau d'Espagne \n sous la seconde République, à part rouge et jaune ?", "A : marron", "B : violet", "C : cyan", "B"],
                    ["Datez la signature du plan Marshall", "A : 1950", "B : 1949", "C : 1947", "C"],
                    ["La marque Samsung est d'origine ?", "A : japonaise", "B : coréenne", "C : vietnamienne", "B"],
                    ["Datez la chute du Mur de Berlin", "A : 1992", "B : 1989", "C : 1990", "B"],
                    ["La Shueisha; au Japon; est ...", "A : une maison d'édition", "B : un siége social", "C une maison de disque","A"],
                    ["La guerre civil espagnole a duré...", "A : 5 ans", "B : 3 ans", "C : 1 ans", "B"],
                    ["Capital du Brésil", "A : Rio de Janeiro", "B : Brasilia", "C : Sao Paulo", "B"],
                    ["Qui est l'auteur de la Joconde ?", "A : Rembrandt", "B : Leonard de Vinci", "Van Gogh", "B"],
                    ["Lequel de ces fruits est un agrume ?", "A : Citron", "B : Banane", "C : Pêche", "A"],
                    ["Un croissant est...", "A : une pâtisserie", "B : Une viennoiserie", "C : Une tarte", "B"],
                    ["Quel peintre se coupa l'oreille ?", "A : Van Gogh", "B : Goya", "C : Cezanne", "A"],]

# Questions de S
questionS = [["Quelle est la forme exponentielle de z= -3i", "A : 4e^iπ/4", "B : 3e^iπ/2", "C : e^iπ/4", "B"],
             ["Les fuseaux neuromusculaires sont à l'origine...", "A : d'un message sensitif","B : d'un message moteur", "C : d'un potentiel de repos","A"],
             ["L'humérus est un os situé dans...", "A : La jambe", "B : Le bras", "C : Le pied", "B : 1976", "C : 1981", "C"],
             ["Quesque la spéciation géographique ?","A : la séparation d'une espèce suite \n à un évènement géographique","B : le réunion d'un espèce suite \n à un évènement géographique","C : la séparation de roches","A"],
             ["Dans un test d'immunodifusion, l'arc de précipitation révèle","A : les antigènes","B : les anticorps","C : les complexes anticorps & antigène ","C"]]

# Questions de L
questionL = [["De quel crime se rend coupable Œdipe ?", " A : parricide", "B : viol", "C : homicide","A"],
             ["Au XIXè siècle, dans quel pays Alexis de Tocqueville a-t-il été mandaté \n par le gouvernement français pour y \n étudier le système pénitentiaire ?","A : l'Angleterre","B: le Canada", "C : Etat-Unis", "C"],
             ["Qui a écrit << La Peste >> ?", "A : Jean-Paul Sartres", "B : Albert Camus", "C : Gustave Flaubert", "B"]]

# Questions de ES
questionES = [["Quelle notion pouvez-vous rattacher au soft power chinois ?", "A : le riz", "B : les mangas", "C : les instituts Confucius", "C"],
              ["Quand a eu lieu la Première Guerre du Golf ?", "A : En 1989-90", "B : En 1990-91", "C : En 1991-92", "B"],
              ["Lequel de ces états est frontalier de la Californie ?", "A : Le Nouveau-Mexique", "B : L'Utah", "C : L'Oregon", "C"],
              ["En quelle année Barack Obama a-t'il obtenue \n le prix nobel de la paix ?", "A : 2009", "B : 2012", "C : 2015", "A"],
              ["En quelle année François Mitterrand a-t-il été élu \n président de la République française ?", "A : 1974", "B :1976", "C : 1981", "C"]]

# Prison
Prison = [["Vous êtes en Prison pour sortir \n il faut faire un 6", "", "", "", ""]]
